In [1]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.functions import col, when, rand, round as spark_round, isnull
import pandas as pd

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 3, Finished, Available, Finished, False)

In [2]:
df = spark.table('bronze.students')

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 4, Finished, Available, Finished, False)

In [3]:
df.columns

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 5, Finished, Available, Finished, False)

['Student_ID',
 'First_Name',
 'Last_Name',
 'Email',
 'Gender',
 'Department',
 'Grade',
 'Extracurricular_Activities',
 'Internet_Access_at_Home',
 'Parent_Education_Level',
 'Family_Income_Level',
 'Age',
 'Math_Score',
 'assi_Math',
 'Science_Score',
 'assi_Science',
 'English_Score',
 'assi_English',
 'Social_Studies_Score',
 'assi_Social_Studie',
 'French_Score',
 'assi_French',
 'Computer_Science_Score',
 'assi_Computer_Science',
 'last_score',
 'Study_Hours_per_Week',
 'Stress_Level_1_10',
 'Sleep_Hours_per_Night',
 'assi_late',
 'non_academic_attendance',
 'academic_attendance',
 'lms_login_freq_per_day',
 'lms_active_avg_hrs',
 'resource_access_avg_hrs']

In [4]:
df = df.dropDuplicates()

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 6, Finished, Available, Finished, False)

In [5]:
df.columns

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 7, Finished, Available, Finished, False)

['Student_ID',
 'First_Name',
 'Last_Name',
 'Email',
 'Gender',
 'Department',
 'Grade',
 'Extracurricular_Activities',
 'Internet_Access_at_Home',
 'Parent_Education_Level',
 'Family_Income_Level',
 'Age',
 'Math_Score',
 'assi_Math',
 'Science_Score',
 'assi_Science',
 'English_Score',
 'assi_English',
 'Social_Studies_Score',
 'assi_Social_Studie',
 'French_Score',
 'assi_French',
 'Computer_Science_Score',
 'assi_Computer_Science',
 'last_score',
 'Study_Hours_per_Week',
 'Stress_Level_1_10',
 'Sleep_Hours_per_Night',
 'assi_late',
 'non_academic_attendance',
 'academic_attendance',
 'lms_login_freq_per_day',
 'lms_active_avg_hrs',
 'resource_access_avg_hrs']

In [6]:
df.describe().toPandas()

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 8, Finished, Available, Finished, False)

,summary,Student_ID,First_Name,Last_Name,Email,Gender,Department,Grade,Extracurricular_Activities,Internet_Access_at_Home,...,last_score,Study_Hours_per_Week,Stress_Level_1_10,Sleep_Hours_per_Night,assi_late,non_academic_attendance,academic_attendance,lms_login_freq_per_day,lms_active_avg_hrs,resource_access_avg_hrs
0,count,2448,2448,2448,2448,2448,2448,2448,2448,2448,...,2448,2448,2448,2448,2001,2001,2001,2001,2001,2001
1,mean,None,None,None,None,None,None,None,None,None,...,73.10502450980405,17.64240196078435,5.4869281045751634,6.50126633986929,0.07269341519440281,82.23191915951523,86.06832893079964,1.7493769186871635,1.5538479569735117,1.0716789224467795
2,stddev,None,None,None,None,None,None,None,None,None,...,11.778259640662704,7.394374834250934,2.886179014011092,1.4637125620775049,0.32004649205770586,8.72184476384738,10.297887666665059,0.4991634996366383,0.2863522484870343,0.23743387453398687
3,min,S1002,Ahmed,Brown,student1003@university.com,Female,5th Grade,B,No,No,...,39.6,5.0,1,4.0,0.0,8.0,42.0,0.6,1.0,0.5
4,max,S5999,Sara,Williams,student99@university.com,Male,Middle School,F,Yes,Yes,...,100.0,30.0,10,9.0,3.0,100.0,100.0,3.0,2.5,1.8

In [7]:
df.filter(
    (col("Student_ID").isNull()) |
    (col("First_Name").isNull()) |
    (col("Last_Name").isNull()) |
    (col("Email").isNull()) |
    (col("Gender").isNull()) |
    (col("Department").isNull()) |
    (col("Grade").isNull()) |
    (col("Extracurricular_Activities").isNull()) |
    (col("Internet_Access_at_Home").isNull()) |
    (col("Parent_Education_Level").isNull()) |
    (col("Family_Income_Level").isNull()) |
    (col("Age").isNull()) |
    (col("Math_Score").isNull()) |
    (col("assi_Math").isNull()) |
    (col("Science_Score").isNull()) |
    (col("assi_Science").isNull()) |
    (col("English_Score").isNull()) |
    (col("assi_English").isNull()) |
    (col("Social_Studies_Score").isNull()) |
    (col("assi_Social_Studie").isNull()) |
    (col("French_Score").isNull()) |
    (col("assi_French").isNull()) |
    (col("Computer_Science_Score").isNull()) |
    (col("assi_Computer_Science").isNull()) |
    (col("last_score").isNull()) |
    (col("Study_Hours_per_Week").isNull()) |
    (col("Stress_Level_1_10").isNull()) |
    (col("Sleep_Hours_per_Night").isNull()) |
    (col("assi_late").isNull()) |
    (col("non_academic_attendance").isNull()) |
    (col("academic_attendance").isNull()) |
    (col("lms_login_freq_per_day").isNull()) |
    (col("lms_active_avg_hrs").isNull()) |
    (col("resource_access_avg_hrs").isNull())
).toPandas()

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 9, Finished, Available, Finished, False)

,Student_ID,First_Name,Last_Name,Email,Gender,Department,Grade,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,...,last_score,Study_Hours_per_Week,Stress_Level_1_10,Sleep_Hours_per_Night,assi_late,non_academic_attendance,academic_attendance,lms_login_freq_per_day,lms_active_avg_hrs,resource_access_avg_hrs
0,S2303,Emma,Smith,student1303@university.com,Female,6th Grade,F,Yes,Yes,Master's,...,94.6,9.9,6,4.5,NaN,NaN,NaN,NaN,NaN,NaN
1,S5843,Emma,Johnson,student4843@university.com,Female,6th Grade,F,No,Yes,Bachelor's,...,87.1,27.4,5,6.1,NaN,NaN,NaN,NaN,NaN,NaN
2,S5949,Omar,Brown,student4949@university.com,Male,Middle School,F,No,Yes,Bachelor's,...,53.5,10.3,6,4.7,NaN,NaN,NaN,NaN,NaN,NaN
3,S3797,Maria,Brown,student2797@university.com,Female,Middle School,F,Yes,No,High School,...,87.3,5.1,5,5.6,NaN,NaN,NaN,NaN,NaN,NaN
4,S3825,Emma,Smith,student2825@university.com,Female,6th Grade,F,No,Yes,PhD,...,96.1,26.0,5,8.3,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,S2323,Emma,Johnson,student1323@university.com,Female,6th Grade,F,Yes,Yes,PhD,...,98.3,13.4,3,6.5,NaN,NaN,NaN,NaN,NaN,NaN
443,S3090,Sara,Smith,student2090@university.com,Female,Middle School,F,Yes,Yes,High School,...,92.3,5.8,3,4.9,NaN,NaN,NaN,NaN,NaN,NaN
444,S4056,Omar,Brown,student3056@university.com,Male,5th Grade,F,Yes,Yes,PhD,...,49.7,8.5,3,4.2,NaN,NaN,NaN,NaN,NaN,NaN
445,S4258,Ali,Davis,student3258@university.com,Male,6th Grade,F,No,Yes,PhD,...,46.1,10.2,10,5.3,NaN,NaN,NaN,NaN,NaN,NaN
446,S4373,Omar,Johnson,student3373@university.com,Male,5th Grade,F,No,Yes,Bachelor's,...,93.3,19.4,5,8.0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
null_counts = df.select([
    sum(when(col(c).isNull(), 1).otherwise(0)).alias(c)
    for c in df.columns
])

display(null_counts)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 10, Finished, Available, Finished, False)

SynapseWidget(Synapse.DataFrame, b7080951-5e43-4b70-8250-c27586950617)

In [9]:
df = df.withColumn("Total_Avg", 
    (col("Math_Score") + col("Science_Score") + col("English_Score") + 
     col("Social_Studies_Score") + col("French_Score") + col("Computer_Science_Score")) / 6
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 11, Finished, Available, Finished, False)

In [10]:
df = df.withColumn("Internet_Access_at_Home",
    when(col("Family_Income_Level") == "High", when(rand() <= 0.95, "Yes").otherwise("No"))
    .when(col("Family_Income_Level") == "Medium", when(rand() <= 0.75, "Yes").otherwise("No"))
    .when(col("Family_Income_Level") == "Low", when(rand() <= 0.35, "Yes").otherwise("No"))
    .otherwise(col("Internet_Access_at_Home"))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 12, Finished, Available, Finished, False)

In [11]:
df = df.withColumn("academic_attendance",
    when(isnull(col("academic_attendance")),
        when(col("Total_Avg") >= 85, spark_round(rand() * (100 - 90) + 90, 2))
        .when(col("Total_Avg") >= 70, spark_round(rand() * (89 - 75) + 75, 2))
        .otherwise(spark_round(rand() * (70 - 50) + 50, 2))
    ).otherwise(col("academic_attendance"))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 13, Finished, Available, Finished, False)

In [12]:
df = df.withColumn("Math_Score",
    when(col("Department") == "Middle School", col("Math_Score") + 12 + (rand() * 6 - 3))
    .when(col("Department") == "6th Grade", col("Math_Score") + 2 + (rand() * 6 - 3))
    .when(col("Department") == "5th Grade", col("Math_Score") - 8 + (rand() * 6 - 3))
    .otherwise(col("Math_Score"))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 14, Finished, Available, Finished, False)

In [13]:
df = df.withColumn("Math_Score", 
    when(col("Math_Score") > 100, 100)
    .when(col("Math_Score") < 0, 0)
    .otherwise(spark_round(col("Math_Score"), 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 15, Finished, Available, Finished, False)

In [14]:
df = df.withColumn("Grade",
    when(col("Total_Avg") >= 88, "A")
    .when(col("Total_Avg") >= 75, "B")
    .when(col("Total_Avg") >= 65, "C")
    .when(col("Total_Avg") >= 50, "D")
    .otherwise("F")
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 16, Finished, Available, Finished, False)

In [15]:
df = df.withColumn("lms_active_avg_hrs",
    when(col("Internet_Access_at_Home") == "No", spark_round(col("lms_active_avg_hrs") * 0.4, 2))
    .otherwise(spark_round(col("lms_active_avg_hrs") * 1.2, 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 17, Finished, Available, Finished, False)

In [16]:
df = df.withColumn("resource_access_avg_hrs",
    when(col("Internet_Access_at_Home") == "No", spark_round(col("resource_access_avg_hrs") * 0.3, 2))
    .otherwise(spark_round(col("resource_access_avg_hrs") * 1.2, 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 18, Finished, Available, Finished, False)

In [17]:
df = df.withColumn("Study_Hours_per_Week",
    when(col("Grade") == "A", spark_round(rand() * (35 - 26) + 26, 1))
    .when(col("Grade") == "B", spark_round(rand() * (26 - 18) + 18, 1))
    .when(col("Grade") == "C", spark_round(rand() * (18 - 12) + 12, 1))
    .when(col("Grade") == "D", spark_round(rand() * (12 - 6) + 6, 1))
    .otherwise(spark_round(rand() * (7 - 2) + 2, 1)) # للراسبين F
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 19, Finished, Available, Finished, False)

In [18]:
df = df.withColumn("Extracurricular_Activities",
    when(col("Grade") == "A", when(rand() <= 0.75, "Yes").otherwise("No"))
    .when(col("Grade") == "B", when(rand() <= 0.55, "Yes").otherwise("No"))
    .when(col("Grade") == "C", when(rand() <= 0.35, "Yes").otherwise("No"))
    .when(col("Grade") == "D", when(rand() <= 0.20, "Yes").otherwise("No"))
    .otherwise(when(rand() <= 0.10, "Yes").otherwise("No"))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 20, Finished, Available, Finished, False)

In [19]:
df = df.withColumn("non-academic_attendance",
    when(col("Extracurricular_Activities") == "Yes", spark_round(rand() * (100 - 75) + 75, 2))
    .otherwise(spark_round(rand() * (65 - 15) + 15, 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 21, Finished, Available, Finished, False)

In [20]:
df = df.withColumn("academic_attendance",
    when(col("Grade") == "A", spark_round(rand() * (100 - 90) + 90, 2))
    .when(col("Grade") == "B", spark_round(rand() * (95 - 80) + 80, 2))
    .when(col("Grade") == "C", spark_round(rand() * (85 - 70) + 70, 2))
    .when(col("Grade") == "D", spark_round(rand() * (75 - 50) + 50, 2))
    .otherwise(spark_round(rand() * (55 - 20) + 20, 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 22, Finished, Available, Finished, False)

In [21]:
df = df.withColumn("lms_login_freq_per_day",
    when(col("Grade") == "A", spark_round(rand() * (3.0 - 2.5) + 2.5, 2))
    .when(col("Grade") == "B", spark_round(rand() * (2.5 - 1.8) + 1.8, 2))
    .when(col("Grade") == "C", spark_round(rand() * (1.8 - 1.2) + 1.2, 2))
    .when(col("Grade") == "D", spark_round(rand() * (1.2 - 0.6) + 0.6, 2))
    .otherwise(spark_round(rand() * (0.6 - 0.1) + 0.1, 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 23, Finished, Available, Finished, False)

In [22]:
df = df.withColumn("resource_access_avg_hrs",
    when(col("Grade") == "A", spark_round(rand() * (2.8 - 2.0) + 2.0, 2))
    .when(col("Grade") == "B", spark_round(rand() * (2.0 - 1.4) + 1.4, 2))
    .when(col("Grade") == "C", spark_round(rand() * (1.4 - 0.9) + 0.9, 2))
    .when(col("Grade") == "D", spark_round(rand() * (0.9 - 0.4) + 0.4, 2))
    .otherwise(spark_round(rand() * (0.4 - 0.1) + 0.1, 2))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 24, Finished, Available, Finished, False)

In [23]:
df = df.withColumn("Sleep_Hours_per_Night",
    when(col("Grade") == "A", spark_round(rand() * (9.0 - 7.5) + 7.5, 1))
    .when(col("Grade") == "B", spark_round(rand() * (8.0 - 6.5) + 6.5, 1))
    .when(col("Grade") == "C", spark_round(rand() * (7.0 - 5.5) + 5.5, 1))
    .when(col("Grade") == "D", spark_round(rand() * (6.0 - 4.5) + 4.5, 1))
    .otherwise(spark_round(rand() * (5.0 - 4.0) + 4.0, 1))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 25, Finished, Available, Finished, False)

In [24]:
df = df.withColumn("Stress_Level_Calc", 
    10 - ((col("Sleep_Hours_per_Night") - 4) / 5) * 8 + (rand() * 2 - 1)
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 26, Finished, Available, Finished, False)

In [25]:
df = df.withColumn("Stress_Level (1-10)",
    when(spark_round(col("Stress_Level_Calc")) > 10, 10)
    .when(spark_round(col("Stress_Level_Calc")) < 1, 1)
    .otherwise(spark_round(col("Stress_Level_Calc")).cast("integer"))
).drop("Stress_Level_Calc")

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 27, Finished, Available, Finished, False)

In [26]:
df = df.withColumn("assi_late",
    when(col("Stress_Level (1-10)") >= 8, spark_round(rand() * (5 - 2) + 2, 0).cast("integer"))
    .when(col("Stress_Level (1-10)") >= 5, spark_round(rand() * (3 - 1) + 1, 0).cast("integer"))
    .otherwise(spark_round(rand() * (2 - 0) + 0, 0).cast("integer"))
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 28, Finished, Available, Finished, False)

In [27]:
df = df.withColumn("assi_late", ceil(col("assi_late")))

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 29, Finished, Available, Finished, False)

In [28]:
df = df.withColumn("id", monotonically_increasing_id())

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 30, Finished, Available, Finished, False)

In [29]:
df = df.select("id", *[c for c in df.columns if c != 'id'])
display(df)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 31, Finished, Available, Finished, False)

SynapseWidget(Synapse.DataFrame, 0dfaa70b-e699-4eac-82b6-ccb55cba5c17)

In [30]:
df = df.drop(
    "non_academic_attendance",
    "Stress_Level_1_10"
)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 32, Finished, Available, Finished, False)

In [31]:
from collections import Counter

Counter(df.columns)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 33, Finished, Available, Finished, False)

Counter({'id': 1,
         'Student_ID': 1,
         'First_Name': 1,
         'Last_Name': 1,
         'Email': 1,
         'Gender': 1,
         'Department': 1,
         'Grade': 1,
         'Extracurricular_Activities': 1,
         'Internet_Access_at_Home': 1,
         'Parent_Education_Level': 1,
         'Family_Income_Level': 1,
         'Age': 1,
         'Math_Score': 1,
         'assi_Math': 1,
         'Science_Score': 1,
         'assi_Science': 1,
         'English_Score': 1,
         'assi_English': 1,
         'Social_Studies_Score': 1,
         'assi_Social_Studie': 1,
         'French_Score': 1,
         'assi_French': 1,
         'Computer_Science_Score': 1,
         'assi_Computer_Science': 1,
         'last_score': 1,
         'Study_Hours_per_Week': 1,
         'Sleep_Hours_per_Night': 1,
         'assi_late': 1,
         'academic_attendance': 1,
         'lms_login_freq_per_day': 1,
         'lms_active_avg_hrs': 1,
         'resource_access_avg_hrs': 1,
         'Total_Avg': 1,
         'non-academic_attendance': 1,
         'Stress_Level (1-10)': 1})

In [32]:
from collections import OrderedDict

unique_cols = list(OrderedDict.fromkeys(df.columns))

df = df.toDF(*unique_cols)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 34, Finished, Available, Finished, False)

In [33]:
from collections import Counter

Counter(df.columns)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 35, Finished, Available, Finished, False)

Counter({'id': 1,
         'Student_ID': 1,
         'First_Name': 1,
         'Last_Name': 1,
         'Email': 1,
         'Gender': 1,
         'Department': 1,
         'Grade': 1,
         'Extracurricular_Activities': 1,
         'Internet_Access_at_Home': 1,
         'Parent_Education_Level': 1,
         'Family_Income_Level': 1,
         'Age': 1,
         'Math_Score': 1,
         'assi_Math': 1,
         'Science_Score': 1,
         'assi_Science': 1,
         'English_Score': 1,
         'assi_English': 1,
         'Social_Studies_Score': 1,
         'assi_Social_Studie': 1,
         'French_Score': 1,
         'assi_French': 1,
         'Computer_Science_Score': 1,
         'assi_Computer_Science': 1,
         'last_score': 1,
         'Study_Hours_per_Week': 1,
         'Sleep_Hours_per_Night': 1,
         'assi_late': 1,
         'academic_attendance': 1,
         'lms_login_freq_per_day': 1,
         'lms_active_avg_hrs': 1,
         'resource_access_avg_hrs': 1,
         'Total_Avg': 1,
         'non-academic_attendance': 1,
         'Stress_Level (1-10)': 1})

In [34]:
df = df.withColumnRenamed(
    "Stress_Level (1-10)",
    "Stress_Level_1_10"
).withColumnRenamed(
    "non-academic_attendance",
    "non_academic_attendance"
)

display(df)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 36, Finished, Available, Finished, False)

SynapseWidget(Synapse.DataFrame, 5a55f69c-5f8c-4a3a-82d4-81b3f1f58ce0)

In [35]:
from collections import Counter

Counter(df.columns)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 37, Finished, Available, Finished, False)

Counter({'id': 1,
         'Student_ID': 1,
         'First_Name': 1,
         'Last_Name': 1,
         'Email': 1,
         'Gender': 1,
         'Department': 1,
         'Grade': 1,
         'Extracurricular_Activities': 1,
         'Internet_Access_at_Home': 1,
         'Parent_Education_Level': 1,
         'Family_Income_Level': 1,
         'Age': 1,
         'Math_Score': 1,
         'assi_Math': 1,
         'Science_Score': 1,
         'assi_Science': 1,
         'English_Score': 1,
         'assi_English': 1,
         'Social_Studies_Score': 1,
         'assi_Social_Studie': 1,
         'French_Score': 1,
         'assi_French': 1,
         'Computer_Science_Score': 1,
         'assi_Computer_Science': 1,
         'last_score': 1,
         'Study_Hours_per_Week': 1,
         'Sleep_Hours_per_Night': 1,
         'assi_late': 1,
         'academic_attendance': 1,
         'lms_login_freq_per_day': 1,
         'lms_active_avg_hrs': 1,
         'resource_access_avg_hrs': 1,
         'Total_Avg': 1,
         'non_academic_attendance': 1,
         'Stress_Level_1_10': 1})

In [36]:
df = df.withColumn("Math_Score", round(col("Math_Score"), 2)) \
    .withColumn("Science_Score", round(col("Science_Score"), 2)) \
    .withColumn("English_Score", round(col("English_Score"), 2)) \
    .withColumn("Social_Studies_Score", round(col("Social_Studies_Score"), 2)) \
    .withColumn("French_Score", round(col("French_Score"), 2)) \
    .withColumn("Computer_Science_Score", round(col("Computer_Science_Score"), 2)) \
    .withColumn("assi_Math", round(col("assi_Math"), 2)) \
    .withColumn("assi_Science", round(col("assi_Science"), 2)) \
    .withColumn("assi_English", round(col("assi_English"), 2)) \
    .withColumn("assi_Social_Studie", round(col("assi_Social_Studie"), 2)) \
    .withColumn("assi_French", round(col("assi_French"), 2)) \
    .withColumn("assi_Computer_Science", round(col("assi_Computer_Science"), 2)) \
    .withColumn("last_score", round(col("last_score"), 2)) \
    .withColumn("Study_Hours_per_Week", round(col("Study_Hours_per_Week"), 2)) \
    .withColumn("Stress_Level_1_10", round(col("Stress_Level_1_10"), 2)) \
    .withColumn("Sleep_Hours_per_Night", round(col("Sleep_Hours_per_Night"), 2)) \
    .withColumn("assi_late", round(col("assi_late"), 2)) \
    .withColumn("non_academic_attendance", round(col("non_academic_attendance"), 2)) \
    .withColumn("academic_attendance", round(col("academic_attendance"), 2)) \
    .withColumn("lms_login_freq_per_day", round(col("lms_login_freq_per_day"), 2)) \
    .withColumn("lms_active_avg_hrs", round(col("lms_active_avg_hrs"), 2)) \
    .withColumn("resource_access_avg_hrs", round(col("resource_access_avg_hrs"), 2))

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 38, Finished, Available, Finished, False)

In [37]:
result = df.groupBy("Gender", "Grade", "Department") \
  .agg(
      avg("assi_late").alias("avg_assi_late"),
      avg("non_academic_attendance").alias("avg_non_academic"),
      avg("academic_attendance").alias("avg_academic"),
      avg("lms_login_freq_per_day").alias("avg_login"),
      avg("lms_active_avg_hrs").alias("avg_lms_hours"),
      avg("resource_access_avg_hrs").alias("avg_resource")
  ) \
  .orderBy("Grade", "Department")

display(result)

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 39, Finished, Available, Finished, False)

SynapseWidget(Synapse.DataFrame, 1417e94a-b447-4103-9595-0f7aa4919a0d)

In [38]:
df.write.format("delta") \
    .mode("overwrite") \
    .saveAsTable("silver.silver_Students")

StatementMeta(, bd0fbbd5-fcfc-4178-ac1d-b74c1bd86830, 40, Finished, Available, Finished, False)